preset: recommended

risky: true

disabled:
  - align_double_arrow
  - concat_without_spaces
  - elseif
  - phpdoc_align

enabled:
  - native_constant_invocation
  - native_function_invocation
  - static_lambda

finder:
  exclude:
    - vendor
  name: "*.php"